name: AUTO_APE_ENV
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip=23.3.1
  - numpy=1.24.3
  - pandas=2.1.4
  - scikit-learn=1.3.0
  - matplotlib=3.8.0
  - scipy=1.11.4
  - catboost=1.2
  - lightgbm=4.1.0
  - xgboost=1.7.3
  - conda-forge::scikit-optimize=0.9.0